/**
 * # Azure Monitor Action Group Module
 *
 * This Terraform module creates and manages an Azure Monitor Action Group, which defines
 * a collection of notification preferences used by Azure Monitor alerts and service health
 * alerts.
 *
 * ## Overview
 *
 * Azure Monitor Action Groups enable you to define reusable collections of notification
 * actions that can be triggered when alerts are fired. This module provides a standardized
 * way to create action groups with consistent naming and tagging conventions.
 *
 * ## Features
 *
 * - **Standardized Naming**: Automatically generates resource names following organizational
 *   standards using the terraform-terraform-namer module
 * - **Automatic Tagging**: Applies consistent tags including environment, location, contact,
 *   and custom tags
 * - **Resource Group Integration**: Deploys into existing resource groups with location
 *   inheritance
 * - **Short Name Validation**: Ensures display names meet Azure's 12-character limit
 * - **Flexible Configuration**: Supports custom display names and optional tags
 *
 * ## Resources Created
 *
 * This module creates the following Azure resources:
 *
 * - **Azure Monitor Action Group** (`azurerm_monitor_action_group.main`)
 *   - Name format: `ag-{resource_suffix}` (where resource_suffix is generated by the namer module)
 *   - Configured with provided display name (short_name)
 *   - Tagged with standardized metadata
 *
 * ## Dependencies
 *
 * This module depends on:
 *
 * - **terraform-terraform-namer**: Local module for generating standardized resource names
 *   and tags. Must be available at `../terraform-terraform-namer`
 * - **AzureRM Provider**: Requires Azure Resource Manager provider to be configured
 * - **Existing Resource Group**: Requires a pre-existing Azure resource group
 *
 * ## Usage Example
 *
 * ```hcl
 * module "action_group" {
 *   source = "./terraform-azurerm-action-group"
 *
 *   display_name   = "CriticalOps"
 *   resource_group = azurerm_resource_group.monitoring
 *
 *   name = {
 *     contact     = "ops@example.com"
 *     environment = "prd"
 *     instance    = 1
 *     program     = "monitoring"
 *     repository  = "terraform-azurerm-action-group"
 *     workload    = "alerts"
 *   }
 *
 *   optional_tags = {
 *     CostCenter = "IT-OPS"
 *     Criticality = "High"
 *   }
 * }
 * ```
 *
 * ## Naming Convention
 *
 * The module generates resource names following this pattern:
 * - Action Group: `ag-{environment}-{location}-{workload}-{instance}`
 *
 * Example: `ag-prd-cus-alerts-001`
 *
 * ## Tagging Strategy
 *
 * All resources are tagged with:
 * - **Contact**: Email address of the responsible team/person
 * - **Environment**: Environment designation (dev, stg, prd, etc.)
 * - **Location**: Azure region abbreviation
 * - **Program**: Program or project name
 * - **Repository**: Source repository name
 * - **Workload**: Workload or application name
 * - **CreateDate**: Resource creation timestamp
 * - **EndDate**: Calculated expiration date
 * - Custom tags from `optional_tags` variable
 *
 * ## Validation
 *
 * The module includes input validation for:
 * - **display_name**: Must be between 1 and 12 characters (Azure requirement)
 * - **expiration_days**: Must be greater than zero
 *
 * ## Best Practices
 *
 * 1. Use descriptive display names that clearly identify the action group's purpose
 * 2. Keep display names under 12 characters due to Azure limitations
 * 3. Define action groups at the monitoring or shared services level
 * 4. Use consistent naming patterns across environments
 * 5. Tag resources appropriately for cost tracking and governance
 * 6. Document the purpose and scope of each action group
 *
 * ## Limitations
 *
 * - Display name (short_name) is limited to 12 characters by Azure
 * - This module creates the action group structure but does not configure receivers
 *   (email, SMS, webhook, etc.). Receivers should be added separately.
 *
 * ## Further Configuration
 *
 * After creating the action group, you may want to:
 * - Add email, SMS, or webhook receivers
 * - Configure Azure Functions or Logic Apps as action endpoints
 * - Associate the action group with alert rules
 * - Set up notification throttling
 *
 * ## Related Modules
 *
 * - `terraform-terraform-namer`: Naming and tagging standardization
 * - `terraform-azurerm-diagnostics`: Diagnostic settings for monitoring
 *
 * ---
 */

#
# Naming Module
#
# Generates standardized resource names and tags according to organizational conventions.
# Uses local module reference for development and testing.
#
module "name" {
  source  = "app.terraform.io/infoex/namer/terraform"
  version = "0.0.2"

  contact       = var.name.contact
  environment   = var.name.environment
  instance      = var.name.instance
  location      = var.is_global ? "global" : var.resource_group.location
  optional_tags = var.optional_tags
  repository    = var.name.repository
  workload      = var.name.workload
}

#
# Azure Monitor Action Group
#
# Creates the action group resource with standardized naming and tagging.
# The action group serves as a container for notification receivers.
#
resource "azurerm_monitor_action_group" "main" {
  name                = "ag-${module.name.resource_suffix}"
  resource_group_name = var.resource_group.name
  short_name          = var.display_name
  tags                = module.name.tags
}

# =============================================================================
# Section: Diagnostics Integration (Optional)
# =============================================================================
# Enable diagnostic settings for Action Group alert activity audit logging

module "diagnostics" {
  count   = var.diagnostics.enabled ? 1 : 0
  source  = "app.terraform.io/infoex/diagnostics/azurerm"
  version = "0.0.6"

  log_analytics_workspace_id = var.diagnostics.log_analytics_workspace_id

  monitored_services = {
    action_group = {
      id      = azurerm_monitor_action_group.main.id
      table   = var.diagnostics.destination_type
      include = [] # Enable all available diagnostic categories
    }
  }
}